# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Skip on updates to .md files.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  files:
    - '**/*.md'

install:
  - cinst pester -y

build: off

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
        }
